### ISSUE TITLE
Select from Query instead of Table

### ISSUE THREAD

**Issue by tkofford** [fbraem/sql-smith#1]
Is there any way to select from a query instead of a table?

Say I was given a complicated query with lots of table joins and conditions, but I wanted to select from it similar to a common table expression (CTE). 

For example, 
Assuming the "query" returns a table like data set and I would filter that data set as normal in the 
`
query = "select field1, field2, ... from table1 inner join table2 inner join table3 ..."
`

Given the above query, I would like to select from it as follows, using the ".from()" from sql-smith, resulting in the following query output:

`SELECT * FROM (query) AS api_query WHERE field1 = 2112`

Is this possible?

**Comment by tkofford** [comment]
I actually just found a workaround by pre-pending a common table expression (CTE) to the generated query. For example,
say I have the following sql-smith code and generated query
```
factory = QueryFactory(CommonEngine())
query = factory \
    .select("*") \
    .from_("api_query") \
    .where(field('field1').eq_(2112)
    .compile()
```
which generates:
`SELECT * FROM "api_query" WHERE "field1" = 2112`
And I have the following CTE:
```
cte = "WITH api_query AS ( SELECT field1, field2, field3 FROM T1 ) "
```
The I can prepend the cte to the sql-smith query and run the resulting query successfully:
`WITH api_query AS ( SELECT field1, field2, field3 FROM T1 ) SELECT * FROM "api_query" WHERE "field1" = 2112`

**Comment by tkofford** [comment]
I'm going to close this issue since I did find a workaround for using common table expressions (CTEs). However, maybe it would be good idea to add a CTE type expression feature?

**Comment by fbraem** [comment]
Is this the same issue as described [here](https://github.com/shadowhand/latitude/issues/37#issuecomment-458969294) ?

**Comment by tkofford** [comment]
Yes @fbraem , that looks to be the same issue, although the CTE syntax is a little different than the simple subselect.

**Comment by fbraem** [comment]
In version 1.1.0, a CTE is now possible using the with_ method on a SelectQuery: https://fbraem.github.io/sql-smith/select.html
